"""
Core app services for loading artefacts and scoring bundles.

This module is a **stable import surface** for Streamlit pages: it re-exports
symbols from ``src.iot_streamlit`` (scoring, paths, session keys) and related
helpers so ``views/*.py`` can use a single ``from src.app_core import …``.

**Where to look for logic**

- Streamlit caches, ``compute_scoring`` / ``score_dataframe``, wizard chrome: ``src/iot_streamlit.py``
- Bundle types + pure metrics: ``src/scoring_types.py``
- Validate + ``build_scoring_bundle`` (transform + Keras): ``src/scoring_engine.py``
- Disk artefact reads: ``src/artifact_loaders.py``; path constants: ``src/iot_paths.py``
- Metrics export payloads / markdown report: ``src/scoring_reports.py``; CSV helpers: ``src/table_io.py``
- UI chrome / wizard stepper: ``src/iot_streamlit.py`` + ``src/ui_helpers.py``
- Colours and layout CSS: ``src/ui_theme.py``
- Wizard session keys / step list: ``src/iot_constants.py``
- File index: ``docs/MODULE_MAP.md``; architecture: ``docs/ARCHITECTURE.md`` (see also ``docs/DESIGN.md``, ``docs/EVALUATION.md``)
"""

from __future__ import annotations

from src.iot_streamlit import (
    CAPTION_ARTEFACT_BATCH_SCORING,
    CAPTION_DATASET_SOURCES_SHORT,
    CAPTION_EVALUATION_ROWS_SCOPE,
    CAPTION_EVALUATION_SCOPE_SHORT,
    CAPTION_HOME_START_HERE,
    CAPTION_PREPARE_MODEL_LEAD,
    CAPTION_SELECT_DATA_LEAD,
    CAPTION_WHERE_EVALUATION_LIVES,
    DATA_PATH,
    DATA_SOURCE_CHOICES,
    FEATURE_COLUMNS_PATH,
    ID_COLUMNS,
    LABEL_COLUMNS,
    LABEL_DATA_SOURCE_PROJECT,
    LABEL_DATA_SOURCE_UPLOAD,
    MARKDOWN_ARTEFACT_BATCH_SCORING,
    MARKDOWN_DATASET_SOURCES_FOR_SCORING,
    MARKDOWN_EVALUATION_SCOPE,
    MARKDOWN_RESTORE_TRAINING_PIPELINE,
    MARKDOWN_WHERE_EVALUATION_LIVES,
    MODEL_PATH,
    PREPROCESSOR_PATH,
    PROJECT_ROOT,
    THRESHOLD_PATH,
    ScoringBundle,
    active_model_path,
    active_threshold,
    app_debug_mode,
    artifact_path_line,
    check_environment,
    check_model_artefacts,
    check_processed_csv_available,
    classification_report_markdown,
    compute_scoring,
    find_saved_baseline_reference,
    friendly_scoring_error,
    load_feature_column_meta,
    list_keras_model_paths,
    load_model,
    load_preprocessor,
    load_raw_dataframe,
    load_scoring_bundle,
    load_threshold,
    model_summary_text,
    missing_label_columns_message,
    parse_csv_bytes,
    reconstruction_mse,
    render_metrics_export_buttons,
    render_sidebar_metrics,
    render_sidebar_placeholder,
    reproducibility_summary_dict,
    reproducibility_summary_json_bytes,
    safe_path_mtime,
    score_dataframe,
    scoring_cache_signature,
    SK_REPAIR_LAST_LOG,
    SK_WIZARD_MODEL_PATH,
    SK_WIZARD_SESSION_THRESHOLD,
    SK_REPAIR_ORIGINAL_DF,
    SK_REPAIR_WORKING_DF,
    SK_WIZARD_DATA_SOURCE,
    SK_WIZARD_UPLOAD_BYTES,
    SK_WIZARD_UPLOAD_NAME,
    stratified_split_counts,
    try_read_processed_csv,
    validate_dataframe_for_scoring,
    render_evaluation_summary_panel,
    render_restore_training_pipeline_ui,
)

__all__ = [
    "CAPTION_ARTEFACT_BATCH_SCORING",
    "CAPTION_DATASET_SOURCES_SHORT",
    "CAPTION_EVALUATION_ROWS_SCOPE",
    "CAPTION_EVALUATION_SCOPE_SHORT",
    "CAPTION_HOME_START_HERE",
    "CAPTION_PREPARE_MODEL_LEAD",
    "CAPTION_SELECT_DATA_LEAD",
    "CAPTION_WHERE_EVALUATION_LIVES",
    "DATA_PATH",
    "DATA_SOURCE_CHOICES",
    "FEATURE_COLUMNS_PATH",
    "ID_COLUMNS",
    "LABEL_COLUMNS",
    "LABEL_DATA_SOURCE_PROJECT",
    "LABEL_DATA_SOURCE_UPLOAD",
    "MARKDOWN_ARTEFACT_BATCH_SCORING",
    "MARKDOWN_DATASET_SOURCES_FOR_SCORING",
    "MARKDOWN_EVALUATION_SCOPE",
    "MARKDOWN_RESTORE_TRAINING_PIPELINE",
    "MARKDOWN_WHERE_EVALUATION_LIVES",
    "MODEL_PATH",
    "PREPROCESSOR_PATH",
    "PROJECT_ROOT",
    "THRESHOLD_PATH",
    "ScoringBundle",
    "active_model_path",
    "active_threshold",
    "app_debug_mode",
    "artifact_path_line",
    "check_environment",
    "check_model_artefacts",
    "check_processed_csv_available",
    "classification_report_markdown",
    "compute_scoring",
    "find_saved_baseline_reference",
    "friendly_scoring_error",
    "load_feature_column_meta",
    "list_keras_model_paths",
    "load_model",
    "load_preprocessor",
    "load_raw_dataframe",
    "load_scoring_bundle",
    "load_threshold",
    "model_summary_text",
    "missing_label_columns_message",
    "parse_csv_bytes",
    "reconstruction_mse",
    "render_metrics_export_buttons",
    "render_evaluation_summary_panel",
    "render_restore_training_pipeline_ui",
    "render_sidebar_metrics",
    "render_sidebar_placeholder",
    "reproducibility_summary_dict",
    "reproducibility_summary_json_bytes",
    "safe_path_mtime",
    "score_dataframe",
    "scoring_cache_signature",
    "SK_REPAIR_LAST_LOG",
    "SK_WIZARD_MODEL_PATH",
    "SK_WIZARD_SESSION_THRESHOLD",
    "SK_REPAIR_ORIGINAL_DF",
    "SK_REPAIR_WORKING_DF",
    "SK_WIZARD_DATA_SOURCE",
    "SK_WIZARD_UPLOAD_BYTES",
    "SK_WIZARD_UPLOAD_NAME",
    "stratified_split_counts",
    "try_read_processed_csv",
    "validate_dataframe_for_scoring",
]
